spring:
  cloud:
    function:
      definition: externalApiFunction

server:
  port: 8080

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
    instances:
      externalApiCB:
        baseConfig: default

logging:
  level:
    root: INFO
    com.mjones3.circuitbreaker: DEBUG